"""
dashboard.py
=============
Terminal-based Student Dropout Risk dashboard with three role views:
    1. Student  - check your own risk score + get recommendations
    2. Faculty  - browse at-risk students in your department
    3. Admin    - system-wide analytics + model performance

Run:
    python3 dashboard.py

Requires (already generated by the training pipeline):
    xgboost_dropout_model.json   (from train_xgboost.py)
    preprocessor.joblib          (from train_xgboost.py)
    student_risk_scores.csv      (from score_all_students.py)
"""

import os
import sys
import joblib
import pandas as pd
from xgboost import XGBClassifier
from pathlib import Path

# Allow imports from the project root when run as `python src/dashboard.py`
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt, FloatPrompt, IntPrompt
from rich.progress import BarColumn, Progress, TextColumn
from rich import box

from src.preprocessing_pipeline import NUMERIC_COLS_V3, CATEGORICAL_COLS_V3
from src.risk_rules import MEDIUM_THRESHOLD as RISK_THRESHOLD, risk_tier  # noqa: F401

console = Console()

BASE_DIR = Path(__file__).resolve().parent.parent

DEPARTMENTS = ["CS", "Engineering", "Business", "Arts", "Science"]
SEMESTERS = ["Year 1", "Year 2", "Year 3", "Year 4"]


# ------------------------------------------------------------
# Shared resources
# ------------------------------------------------------------
def load_resources():
    try:
        model = XGBClassifier()
        model.load_model(BASE_DIR / "models" / "xgboost_dropout_model.json")
        preprocessor = joblib.load(BASE_DIR / "models" / "preprocessor.joblib")
        roster = pd.read_csv(BASE_DIR / "dataset" / "processed" / "student_risk_scores.csv")
    except Exception as e:
        console.print(f"[bold red]Failed to load model/data: {e}[/bold red]")
        console.print("Run 'python3 train_xgboost.py --dataset v3' then "
                       "'python3 score_all_students.py' first.")
        sys.exit(1)
    return model, preprocessor, roster


def risk_tier(p: float) -> str:
    if p >= 0.5:
        return "High"
    elif p >= RISK_THRESHOLD:
        return "Medium"
    return "Low"


def tier_color(tier: str) -> str:
    return {"High": "bold red", "Medium": "bold yellow", "Low": "bold green"}[tier]


def risk_bar(p: float, width: int = 30) -> str:
    filled = int(p * width)
    color = "red" if p >= 0.5 else ("yellow" if p >= RISK_THRESHOLD else "green")
    return f"[{color}]{'█' * filled}{'░' * (width - filled)}[/{color}] {p:.1%}"


def recommendations_for(row) -> list:
    """Simple rule-based recommendations from the strongest risk drivers."""
    recs = []
    if row.get("Attendance_Rate", 100) < 75:
        recs.append("Attendance below 75% — flag for an advising check-in.")
    if row.get("GPA", 4) < 2.0:
        recs.append("Low GPA — recommend tutoring / academic support referral.")
    if row.get("Stress_Index", 0) >= 7:
        recs.append("High stress index — suggest counseling / wellness resources.")
    if row.get("Assignment_Delay_Days", 0) and row.get("Assignment_Delay_Days", 0) >= 5:
        recs.append("Frequent late assignments — check in on workload/time management.")
    if not recs:
        recs.append("No major red flags detected — continue routine monitoring.")
    return recs


# ------------------------------------------------------------
# STUDENT DASHBOARD
# ------------------------------------------------------------
def student_dashboard(model, preprocessor, roster):
    console.rule("[bold cyan]Student Dashboard")
    mode = Prompt.ask(
        "Look up by [1] Student ID  or  [2] Enter my own details",
        choices=["1", "2"], default="1"
    )

    if mode == "1":
        sid = IntPrompt.ask("Enter your Student ID (1-10000)")
        match = roster[roster["Student_ID"] == sid]
        if match.empty:
            console.print(f"[red]No student found with ID {sid}[/red]")
            return
        row = match.iloc[0]
        proba = row["Risk_Probability"]
        tier = row["Risk_Tier"]
        details = row.to_dict()
    else:
        console.print("[dim]Enter your details (press Enter for defaults where shown)[/dim]")
        details = {
            "Age": FloatPrompt.ask("Age", default=20),
            "Family_Income": FloatPrompt.ask("Family income (annual)", default=30000),
            "Study_Hours_per_Day": FloatPrompt.ask("Study hours per day", default=2.5),
            "Attendance_Rate": FloatPrompt.ask("Attendance rate (%)", default=85),
            "Assignment_Delay_Days": IntPrompt.ask("Avg assignment delay (days)", default=1),
            "Travel_Time_Minutes": FloatPrompt.ask("Travel time to campus (min)", default=30),
            "Stress_Index": FloatPrompt.ask("Stress index (0-10)", default=5),
            "GPA": FloatPrompt.ask("Current GPA (0-4)", default=3.0),
            "Semester_GPA": FloatPrompt.ask("Semester GPA (0-4)", default=3.0),
            "CGPA": FloatPrompt.ask("Cumulative GPA (0-4)", default=3.0),
            "Gender": Prompt.ask("Gender", choices=["Male", "Female"], default="Male"),
            "Internet_Access": Prompt.ask("Internet access", choices=["Yes", "No"], default="Yes"),
            "Part_Time_Job": Prompt.ask("Part-time job", choices=["Yes", "No"], default="No"),
            "Scholarship": Prompt.ask("Scholarship", choices=["Yes", "No"], default="No"),
            "Department": Prompt.ask("Department", choices=DEPARTMENTS, default="CS"),
            "Semester": Prompt.ask("Year", choices=SEMESTERS, default="Year 1"),
            "Parental_Education": Prompt.ask(
                "Parental education",
                choices=["High School", "Bachelor", "Master", "PhD"], default="Bachelor"
            ),
        }
        student_df = pd.DataFrame([details])
        student_df["GPA_Decline"] = student_df["GPA"] - student_df["Semester_GPA"]
        student_df["Low_Attendance_Flag"] = (student_df["Attendance_Rate"] < 75).astype(int)
        student_df["Engagement_Score"] = (
            student_df["Study_Hours_per_Day"] - 0.1 * student_df["Assignment_Delay_Days"]
        )
        X = preprocessor.transform(student_df[NUMERIC_COLS_V3 + CATEGORICAL_COLS_V3])
        proba = model.predict_proba(X)[:, 1][0]
        tier = risk_tier(proba)

    console.print()
    console.print(Panel(
        f"[bold]Dropout risk probability:[/bold] {risk_bar(proba)}\n"
        f"[bold]Risk tier:[/bold] [{tier_color(tier)}]{tier}[/{tier_color(tier)}]",
        title="Your Result", border_style=tier_color(tier).split()[-1]
    ))

    table = Table(title="Recommended Next Steps", box=box.SIMPLE)
    table.add_column("#", style="dim", width=3)
    table.add_column("Recommendation")
    for i, rec in enumerate(recommendations_for(details), 1):
        table.add_row(str(i), rec)
    console.print(table)


# ------------------------------------------------------------
# FACULTY DASHBOARD
# ------------------------------------------------------------
def faculty_dashboard(roster):
    console.rule("[bold cyan]Faculty Dashboard")
    dept = Prompt.ask("Select your department", choices=DEPARTMENTS)
    year = Prompt.ask("Filter by year (or 'All')", choices=SEMESTERS + ["All"], default="All")

    sub = roster[roster["Department"] == dept]
    if year != "All":
        sub = sub[sub["Semester"] == year]

    counts = sub["Risk_Tier"].value_counts().reindex(["High", "Medium", "Low"], fill_value=0)
    console.print(Panel(
        f"[bold red]High risk:[/bold red] {counts['High']}    "
        f"[bold yellow]Medium risk:[/bold yellow] {counts['Medium']}    "
        f"[bold green]Low risk:[/bold green] {counts['Low']}    "
        f"[dim]Total: {len(sub)}[/dim]",
        title=f"{dept} — {year}"
    ))

    at_risk = sub[sub["Risk_Tier"].isin(["High", "Medium"])].sort_values(
        "Risk_Probability", ascending=False
    ).head(25)

    table = Table(title="Students needing attention (top 25 by risk)", box=box.SIMPLE_HEAVY)
    table.add_column("Student ID")
    table.add_column("Year")
    table.add_column("Attendance %")
    table.add_column("GPA")
    table.add_column("Stress")
    table.add_column("Risk")
    table.add_column("Tier")
    for _, r in at_risk.iterrows():
        table.add_row(
            str(r["Student_ID"]), r["Semester"], f"{r['Attendance_Rate']:.1f}",
            f"{r['GPA']:.2f}", f"{r['Stress_Index']:.1f}" if pd.notna(r["Stress_Index"]) else "—",
            f"{r['Risk_Probability']:.1%}",
            f"[{tier_color(r['Risk_Tier'])}]{r['Risk_Tier']}[/{tier_color(r['Risk_Tier'])}]",
        )
    console.print(table)
    if at_risk.empty:
        console.print("[green]No at-risk students in this filter. 🎉[/green]")


# ------------------------------------------------------------
# ADMIN DASHBOARD
# ------------------------------------------------------------
def admin_dashboard(roster):
    console.rule("[bold cyan]Admin Dashboard")

    total = len(roster)
    dropout_rate = roster["Actual_Dropout"].mean()
    high = (roster["Risk_Tier"] == "High").sum()
    medium = (roster["Risk_Tier"] == "Medium").sum()

    console.print(Panel(
        f"Total students: [bold]{total:,}[/bold]\n"
        f"Historical dropout rate: [bold]{dropout_rate:.1%}[/bold]\n"
        f"Currently flagged High risk: [bold red]{high:,}[/bold red]\n"
        f"Currently flagged Medium risk: [bold yellow]{medium:,}[/bold yellow]",
        title="Institution Overview"
    ))

    console.print("\n[bold]Model performance (held-out test set)[/bold]")
    perf = Table(box=box.SIMPLE)
    perf.add_column("Metric")
    perf.add_column("Value")
    for m, v in [
        ("Accuracy", "81%"), ("Dropout recall", "48% (baseline) / 75%+ at tuned threshold"),
        ("Dropout precision", "62% (baseline)"), ("ROC-AUC", "0.807"),
    ]:
        perf.add_row(m, v)
    console.print(perf)
    console.print("[dim]Re-run test_xgboost_model.py for fresh numbers after retraining.[/dim]\n")

    console.print("[bold]Dropout risk by department[/bold]")
    by_dept = roster.groupby("Department")["Risk_Probability"].mean().sort_values(ascending=False)
    for dept, avg in by_dept.items():
        console.print(f"{dept:<12} {risk_bar(avg, width=25)}")

    console.print("\n[bold]Dropout risk by year[/bold]")
    by_year = roster.groupby("Semester")["Risk_Probability"].mean().reindex(SEMESTERS)
    for yr, avg in by_year.items():
        console.print(f"{yr:<12} {risk_bar(avg, width=25)}")


# ------------------------------------------------------------
# MAIN MENU
# ------------------------------------------------------------
def main():
    console.print(Panel.fit(
        "[bold]Student Dropout Risk — Terminal Dashboard[/bold]\n"
        "Powered by the XGBoost model in xgboost_dropout_model.json",
        border_style="cyan"
    ))
    model, preprocessor, roster = load_resources()

    while True:
        console.print()
        role = Prompt.ask(
            "Choose a dashboard",
            choices=["student", "faculty", "admin", "quit"],
            default="student"
        )
        if role == "student":
            student_dashboard(model, preprocessor, roster)
        elif role == "faculty":
            faculty_dashboard(roster)
        elif role == "admin":
            admin_dashboard(roster)
        else:
            console.print("[dim]Goodbye![/dim]")
            break


if __name__ == "__main__":
    main()
